### PR TITLE
[WIP] English Grammar Revision

### PR DESCRIPTION
**Pull request by Still34**
# Summary

This PR is a work-in-progress. This PR fixes various English grammar and spelling mistakes found in documentation and or general files such as `README.md`.

### CODE REVIEW

**Comment by Still34** [comment]
The current `README.md` refers to the example `README.md` for more detailed CLI instructions; however, in line 19 of the same file, it refers the `README.md` for Chinese instructions. To keep in line with the overall language, `example/README.md` should be translated into English while the original CHT text should be kept in a separate file (e.g. `README.zh-TW.md`). This is open for discussion.

**Comment by kevinbird61** [comment]
Big thanks!

**Comment by Still34** [comment]
This was meant to be a work-in-progress with extended discussion, but guess we could open a separate issue for that. 🤔

**Comment by kevinbird61** [comment]
Oh, in deed, currently `README.md` was a mess. 
It need an effort to separate them into different file.

**Pull request merged**
